### ISSUE TITLE
BM25 implementation questions

### ISSUE THREAD

**Issue by christophsk** [summanlp/textrank#32]
- Did you use the Gensim implementation for BM25?
- Did you include your IDF modifications in BM25+ ?

**Comment by fedelopez77** [comment]
Hi @christophsk,
1. No, we used [this implementation](https://github.com/summanlp/textrank/blob/exp/17-bm25/summa/bm25.py) of BM25, which is basically the same than you can find on [wikipedia](https://en.wikipedia.org/wiki/Okapi_BM25).
2. In [this implementation](https://github.com/summanlp/textrank/blob/exp/17.2-bm25IdfEpsilon/summa/bm25.py) (see that it is a different branch) we added the epsilon modification described in the [paper](https://arxiv.org/pdf/1602.03606.pdf) that changed a bit the results.

**Comment by christophsk** [comment]
Thank you very much.

**Comment by christophsk** [comment]
I'm 'hardening' this up for production work. One pathological case I ran into was a domain
exception (`ValueError`) with, (in your implementation):
```
for k, v in self.df.items():
       self.idf[k] = math.log(self.D-v+0.5)-math.log(v+0.5)
```
when `v + 0.5` > `self.D`. I wrapped this in `try/except` and raise the exception. I'm
not sure there's a more elegant or accepted way of handling it. 

Thoughts?

**Comment by fedelopez77** [comment]
According to the logic of [this implementation](https://github.com/summanlp/textrank/blob/exp/17-bm25/summa/bm25.py), if a word is present in every document, then `v` will be equal to `self.D`, therefore the calculation will be:
`self.idf[k] = math.log(0.5) - math.log( v + 0.5)` whereas `v` is a natural value (integer > 0).

Can you provide an example where this function raises an exception due to that calculation?

**Comment by christophsk** [comment]
After careful checking, it was a bug in my code (of course!)... Thanks for your help.
