### ISSUE TITLE
Why did not you use iterative method here?

### ISSUE THREAD

**Issue by CoinCheung** [summanlp/textrank#77]
Hi, 

I am reading the so as to know better how this algorithm work. Here I met a question about the code, it is about this line:  
https://github.com/summanlp/textrank/blob/d9252a233c93ec43693e0f145a025ae534b275b1/summa/summarizer.py#L3

If I did not misunderstood the page-rank algorithm, it is an application of markov matrix, which iteratively computes the status according to the transforming matrix. However, from the code, I see that you imported the pagerank_weighted_scipy as the `_pagerank` method, which is only one iteration of the status transformation process ?  It seems that the `pagerank_weighted` has the iteration process but `pagerank_weighted_scipy` is only one iteration of the loop ?

**Comment by fedelopez77** [comment]
Hi,

As you can see in:
https://nlp.stanford.edu/IR-book/html/htmledition/markov-chains-1.html
and in
https://nlp.stanford.edu/IR-book/html/htmledition/the-pagerank-computation-1.html
computing the left eigenvector associated to the main eigenvalue (which is 1) is equal to computing PageRank. And that is exactly what we are doing in the line:
https://github.com/summanlp/textrank/blob/d9252a233c93ec43693e0f145a025ae534b275b1/summa/pagerank_weighted.py#L47

So, instead of using the iterative computation of PageRank, we just use SciPy to obtain the main left eigenvector of the transition probability matrix.

I hope that clarifies your doubts, so let me know if we can close this issue.

**Comment by CoinCheung** [comment]
Thanks for replying!!! From the link you left above, I got to know that the equilibrium of markov chain is the eigenvector(corresponding eigenvalue is 1) of the transform matrix as: `v * M = 1 * v`. But from my limited knowledge of matrix theory, I know that a matrix can have infinite eigenvectors but the eigenvalues are fixed. Is there any mathematical basis to show that markov transform matrix always has an eigenvalue of 1 ?

**Comment by fedelopez77** [comment]
The Markov transform matrix is a [stochastic matrix](https://en.wikipedia.org/wiki/Stochastic_matrix). The [Perron–Frobenius theorem](https://en.wikipedia.org/wiki/Perron%E2%80%93Frobenius_theorem) ensures that every irreducible stochastic matrix has a stationary vector, and that the largest absolute value of an eigenvalue is always 1.
You can find explanations of the proof in the two previous links or just google more simplified explanations.
Thank you for your interest!

**Comment by Zero-coder** [comment]
it really helps，thanks for you guys conversation.
